### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by swatgunner123** [Project-Mega-Pack/amp-aircraft-a330-300#95] opened 2021-03-05 16:16 UTC
A330 COCKPIT DISAPPEARS AND NOT INTERACTIVE.

During a flight normally at cruise i've experienced a bug where the engines stop rotating while flying and the cockpit buttons disappear and I am not able to press any buttons as it's just a smudge. The planes flies and moves normal though. This bug stayed with me for 1 hour and then it went back to normal. I didn't touch my pc or do anything for that 1 hour and switiching camera view did not fix this. I went AFK for an hour and suddenly it came back to normal. I have images here.
![unknown (1)](https://user-images.githubusercontent.com/51244126/110142372-ffe69000-7dcd-11eb-9221-f6afc7a357b0.png)

![unknown (2) pnghjjhg](https://user-images.githubusercontent.com/51244126/110142519-273d5d00-7dce-11eb-9702-3d52ee55530b.png)

**Comment by Clink1234** [comment] 2021-03-05 18:08
Duplicate of #13

**Closed by Clink1234** 2021-03-05 18:08 UTC
Labels: bug
