### ISSUE TITLE
Textures, animations quit working mid flight?[BUG]

### ISSUE THREAD

**Issue by dprotus** [Project-Mega-Pack/amp-aircraft-a330-300#106] opened 2021-03-06 15:14 UTC
Middle of flight at cruise textures and engine animations quit working. 
![Capture](https://user-images.githubusercontent.com/80164332/110211446-471b6200-7e5c-11eb-991e-76cf2b047b85.PNG)
![Capture1](https://user-images.githubusercontent.com/80164332/110211465-4e427000-7e5c-11eb-8c3d-79bc4441031f.PNG)
![Capture2](https://user-images.githubusercontent.com/80164332/110211473-526e8d80-7e5c-11eb-8b06-3ee185df8d6f.PNG)

**Comment by dprotus** [comment] 2021-03-06 15:15
Forgot to add nothing in my community folder other than the A330 and its liveries.

**Comment by Clink1234** [comment] 2021-03-06 18:37
Duplicate of #13

**Closed by Clink1234** 2021-03-06 18:37 UTC
Labels: bug
