### ISSUE TITLE
Issue with Speed Control

### ISSUE THREAD

**Issue by clubsceneuk2** [Project-Mega-Pack/amp-aircraft-a330-300#115] opened 2021-03-08 16:27 UTC
**Description**
When in a descent and the plane hits 5000ft the autopilot suddenly boosts the speed up instead of leaving it as is. 

**Steps to reproduce**
1. Fly from anywhere to anywhere and go above FL10. Use manual ALT and VS control
2. Allow ATC to give you commands to descend
3. as you descend past FL5000 the plane suddenly throttles up well past the speed limit

**Expected behavior**
Speed remains the same and as you use flaps it auto slows the throttle speed down for landing

**Screenshots**
Non Available.

**Additional context**

**Comment by Clink1234** [comment] 2021-03-09 05:48
duplicate of #22

**Closed by Clink1234** 2021-03-09 05:48 UTC
Labels: bug
