### ISSUE TITLE
[BUG] Wrong RCA height indication

### ISSUE THREAD

**Issue by Chumiaczek** [Project-Mega-Pack/amp-aircraft-a330-300#21] opened 2021-03-01 22:59 UTC
**Description**

The main problem with the bug is very simple. When you approach the landing, you will experience that RCA is correct. But just when you flare, you notice that you have a touchdown, even though RCA clearly states it’s still about 10 feet till you will touchdown. After you end your flare and bring your nose down, it will still report 5 feet till touchdown.

**Steps to reproduce**

As I tested it in Europe, try reproducing it there (EGLL airport)

1. Takeoff from other airport as you would normally do
2. At the approach phase, closely monitor RCA callouts
3. When on final, be sure to have RCA callouts in clear view
4. On flare, you should notice that on touchdown you will still have about 10 feet till touchdown.
5. After you end your flare, it will still say 5 feet till touchdown

**Expected behavior**

It should obviously say 0 on touchdown, although due to it’s tilted gear, it might say 1 or 2. After touchdown and the end of flare, RCA shouldn’t be visible at all.

**Screenshots**

I do not have any ScreenShots as for now. Easyjetsimpilot did a live stream testing A330. You can check there for how it looks.
Here’s the link: https://youtu.be/su73s1vnWZE

**Additional context**

Great Freeware Aircraft, with some fixes it will be definitely a huge pleasure to fly with! Thanks for your hard work :).

**Comment by Clink1234** [comment] 2021-03-01 23:05
Duplicate of #20

**Closed by Clink1234** 2021-03-01 23:05 UTC
Labels: bug
