### ISSUE TITLE
Low area in fuselage 

### ISSUE THREAD

**Issue by Winter-huntsman** [Project-Mega-Pack/amp-aircraft-a330-300#55] opened 2021-03-03 07:11 UTC
Looking at the side of the plane, one can see the front looks kinda bulbous. On inspection this is actually caused by the area near where the front of the wing connects to the body of the plane being raised up higher than where it normally is behind and in front, creating the bulbous look. I can apply a photo with this area circled if need be.

Leveling this spot on the underside of the plane with the rest of the fuselage will greatly improve the quality of the planes body.
Also to add on the top part at the front (above cockpit to start of wings) is a little high but not as bad of a difference as the low section mentioned above. It’s hight creates a slope that technically shouldn’t be there.

**Comment by Clink1234** [comment] 2021-03-03 18:12
duplicate of #14

**Closed by Clink1234** 2021-03-03 18:12 UTC
